
spring:
  application:
    name: cloud-user-service
server:
  port: 8082
eureka:
  client:
    fetch-registry: true #是否从eureka获取注册信息
    register-with-eureka: true #是否要将自己注册到eureka上去
    service-url:
      defaultZone: http://root:123456@localhost:8866/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1 #心跳时间
    lease-expiration-duration-in-seconds: 2 #让eureka检测心跳的异常间隔时间
logging:
  file: /cloudUserService/cloudUserService.log
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
#    reactor.ipc.netty: DEBUG

swagger:
  title: 用户服务1
  description: 提供用户服务接口1
  base-package: com.jiayaxing.clouddemo.clouduserservice.controller
  enabled: true  #http://localhost:8082/swagger-ui.html即可访问swagger

#Apollo相关配置
app:
  id: demoApollo
# set apollo meta server address, adjust to actual address if necessary
apollo:
  meta: http://192.168.1.162:8080

